POST https://example.com/comments HTTP/1.1
content-type: application/json

{
    "name": "sample",
    "time": "Wed, 21 Oct 2015 18:27:50 GMT"
}

###
POST https://example.com/comments HTTP/1.1
content-type: application/json

{
    "name": "sample",
    "time": "Wed, 21 Oct 2015 18:27:50 GMT"
}

###
GET http://localhost:3001/api/conductores/ 

###

POST http://localhost:3001/api/logindrivers/
content-type: application/json

{
    "correo_conductor": "ana@gmail.com",
    "contraseña": "12345"
}

###
GET http://localhost:3001/api/conductores/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzQ4NDAwMzc5LCJleHAiOjE3NDg0MDM5Nzl9.61KHmQe7dpK6Rs0IlytnJorEbmd3U8YsK4YHLjdIgbo

###
POST http://localhost:3001/api/conductores/
content-type: application/json

{
  "id_conductor": "2",
  "tipo_documento": "cedula",
  "documento": "19827732",
  "nombre_conductor": "Nacho",
  "apellido_conductor": "Suarez",
  "correo_conductor": "nacho@gmail.com",
  "foto": "sabasjsaj",
  "telefono": "3222488484",
  "ciudad": "Aguascalientes",
  "direccion": "méxico",
  "tipo_licencia": "A2",
  "fecha_vencimiento": "2025-05-31",
  "experiencia": "15"
}

###
//Probar sin comillas//
GET http://localhost:3001/api/vehicles/
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiaWF0IjoxNzQ5MTc5MDc2LCJleHAiOjE3NDkxODk4NzZ9.NUDB_Uw9kP6O2mdXavcsmKQkbriiVAZqe350Ne8dgmU
 
###
GET http://localhost:tu-puerto/api/sales